import './globals.css';
import StoryblokProvider from '@/components/StoryblokProvider';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { getStoryblokApi } from '@/lib/storyblok';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	const storyblokApi = getStoryblokApi();
	const { data } = await storyblokApi.get('cdn/stories/config', { version: 'draft' });
	const config = data.story.content;

	return (
		<StoryblokProvider>
			<html lang="sv">
				<body>
					<Header navLinks={config.header} />
					<main className="max-w-5xl mx-auto px-4 py-8">{children}</main>
					<Footer text={config.footer_text} />
				</body>
			</html>
		</StoryblokProvider>
	);
}
